name: artepuebla
description: "Un proyecto ambientado en los museos ."
publish_to: 'none' # Para evitar publicaiones accidentales en pub.dev

# Configuracion de la version
version: 1.0.0+1

#Ambiente necesario
environment:
  sdk: ^3.5.3

#Dependencias principales
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6 # Añadido para soporte SVG
  http: ^1.2.2 #Para manejar solicitudes HTTP
  cupertino_icons: ^1.0.8 #Iconos estilo iOS
  intl: ^0.18.0
  provider: ^6.0.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.8.0
  google_sign_in: ^6.2.2


#Dependencias para desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 #Buenas practicas y recomendaciones de codificacion
  

#Dependencia para el icono
flutter_icons:
  android: true 
  ios: true
  image_path: "resources/assets/app_icon.png" #Ruta del icono principal
  adaptive_icon_background: "#ffffff" #Fondo blanco

flutter:
  uses-material-design: true
  #Archivos de recursos (assets)
  #assets:
