name: artepuebla
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.6 # Añadido para soporte SVG
  http: ^1.2.2
  provider: ^6.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/images/museo1.jpg
    - assets/images/museo2.jpg
    - assets/images/museo3.jpg
    - assets/images/fachadamuseoevo.jpg
    - assets/images/fachadamuseoamapa.jpg
    - assets/images/fachadamuseoferro.jpg
    - assets/images/Museo_Ferrocarril_Puebla.jpg
    - assets/images/Museo_Amparo_Puebla.jpg
    - assets/images/Museo_Evolucion_Puebla.jpg
    - assets/images/google_color_icon.svg

  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/Ubahn.ttf
        # - asset: assets/fonts/Smooth.ttf
          weight: 700

